### ISSUE TITLE
Error when "make tools"

### ISSUE THREAD

**Issue by Katospiegel** [qnzhou/PyMesh#35]
Hello, I'm using Ubuntu 16.04. After many trials and error I could install all the dependencies and now when I try to use "make tools" I get this error:

`[ 19%] Built target Mesh
[ 19%] Building CXX object tools/IGL/CMakeFiles/lib_igl.dir/MinkowskiSum.cpp.o
In file included from /home/vivar/tools/PyMesh/third_party/libigl/include/igl/copyleft/cgal/../../edges.cpp:9:0,
                 from /home/vivar/tools/PyMesh/third_party/libigl/include/igl/copyleft/cgal/../../edges.h:34,
                 from /home/vivar/tools/PyMesh/third_party/libigl/include/igl/copyleft/cgal/minkowski_sum.cpp:14,
                 from /home/vivar/tools/PyMesh/third_party/libigl/include/igl/copyleft/cgal/minkowski_sum.h:107,
                 from /home/vivar/tools/PyMesh/tools/IGL/MinkowskiSum.cpp:4:
/home/vivar/tools/PyMesh/third_party/libigl/include/igl/copyleft/cgal/../../adjacency_matrix.h:12:0: warning: "EIGEN_YES_I_KNOW_SPARSE_MODULE_IS_NOT_STABLE_YET" redefined
 #define EIGEN_YES_I_KNOW_SPARSE_MODULE_IS_NOT_STABLE_YET
 ^
<command-line>:0:0: note: this is the location of the previous definition
In file included from /usr/include/eigen3/Eigen/Core:366:0,
                 from /home/vivar/tools/PyMesh/src/Core/EigenTypedef.h:4,
                 from /home/vivar/tools/PyMesh/tools/IGL/MinkowskiSum.h:5,
                 from /home/vivar/tools/PyMesh/tools/IGL/MinkowskiSum.cpp:2:
/home/vivar/tools/PyMesh/third_party/libigl/include/igl/copyleft/cgal/minkowski_sum.cpp: In instantiation of ‘void igl::copyleft::cgal::minkowski_sum(const Eigen::PlainObjectBase<Derived>&, const Eigen::PlainObjectBase<DerivedFA>&, const Eigen::Matrix<sType, 1, sCols, sOptions>&, const Eigen::Matrix<dType, 1, dCols, dOptions>&, bool, Eigen::PlainObjectBase<DerivedW>&, Eigen::PlainObjectBase<DerivedG>&, Eigen::PlainObjectBase<DerivedJ>&) [with DerivedVA = Eigen::Matrix<double, -1, -1, 1>; DerivedFA = Eigen::Matrix<int, -1, -1, 1>; sType = double; int sCols = 3; int sOptions = 1; dType = double; int dCols = 3; int dOptions = 1; DerivedW = Eigen::Matrix<double, -1, -1, 1>; DerivedG = Eigen::Matrix<int, -1, -1, 1>; DerivedJ = Eigen::Matrix<int, -1, 1>]’:
/home/vivar/tools/PyMesh/third_party/libigl/include/igl/copyleft/cgal/minkowski_sum.cpp:370:23:   required from ‘void igl::copyleft::cgal::minkowski_sum(const Eigen::PlainObjectBase<Derived>&, const Eigen::PlainObjectBase<DerivedFA>&, const Eigen::Matrix<sType, 1, sCols, sOptions>&, const Eigen::Matrix<dType, 1, dCols, dOptions>&, Eigen::PlainObjectBase<DerivedW>&, Eigen::PlainObjectBase<DerivedG>&, Eigen::PlainObjectBase<DerivedJ>&) [with DerivedVA = Eigen::Matrix<double, -1, -1, 1>; DerivedFA = Eigen::Matrix<int, -1, -1, 1>; sType = double; int sCols = 3; int sOptions = 1; dType = double; int dCols = 3; int dOptions = 1; DerivedW = Eigen::Matrix<double, -1, -1, 1>; DerivedG = Eigen::Matrix<int, -1, -1, 1>; DerivedJ = Eigen::Matrix<int, -1, 1>]’
/home/vivar/tools/PyMesh/tools/IGL/MinkowskiSum.cpp:45:30:   required from here
/usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:482:22: error: ‘Eigen::PlainObjectBase<Derived>& Eigen::PlainObjectBase<Derived>::operator=(Eigen::PlainObjectBase<Derived>&&) [with Derived = Eigen::Matrix<int, -1, 1>]’ is protected
     PlainObjectBase& operator=(PlainObjectBase&& other)
                      ^
In file included from /home/vivar/tools/PyMesh/third_party/libigl/include/igl/copyleft/cgal/minkowski_sum.h:107:0,
                 from /home/vivar/tools/PyMesh/tools/IGL/MinkowskiSum.cpp:4:
/home/vivar/tools/PyMesh/third_party/libigl/include/igl/copyleft/cgal/minkowski_sum.cpp:349:7: error: within this context
     J = slice(DerivedJ(J),SJ,1);
       ^
tools/IGL/CMakeFiles/lib_igl.dir/build.make:86: recipe for target 'tools/IGL/CMakeFiles/lib_igl.dir/MinkowskiSum.cpp.o' failed
make[3]: *** [tools/IGL/CMakeFiles/lib_igl.dir/MinkowskiSum.cpp.o] Error 1
CMakeFiles/Makefile2:3097: recipe for target 'tools/IGL/CMakeFiles/lib_igl.dir/all' failed
make[2]: *** [tools/IGL/CMakeFiles/lib_igl.dir/all] Error 2
CMakeFiles/Makefile2:263: recipe for target 'tools/CMakeFiles/tools.dir/rule' failed
make[1]: *** [tools/CMakeFiles/tools.dir/rule] Error 2
Makefile:144: recipe for target 'tools' failed
make: *** [tools] Error 2
`

Any idea? Thanks in advance

**Comment by qnzhou** [comment]
I have updated libigl in master branch.  Could `git pull` and `git submodule update third_party/libigl`?

As a sanity check, my libigl is at:
```
$ git submodule status third_party/libigl/
 f31d6a9edcb285682afe67f8212ecadc8f863eb4 third_party/libigl (heads/master)
```

**Comment by Katospiegel** [comment]
I updated libigl submodule and checked the status but the same error appear

```
Scanning dependencies of target lib_igl
[ 19%] Building CXX object tools/IGL/CMakeFiles/lib_igl.dir/CellPartition.cpp.o
[ 19%] Building CXX object tools/IGL/CMakeFiles/lib_igl.dir/MinkowskiSum.cpp.o
In file included from /home/vivar/tools/PyMesh/third_party/libigl/include/igl/copyleft/cgal/../../slice_mask.cpp:10:0,
                 from /home/vivar/tools/PyMesh/third_party/libigl/include/igl/copyleft/cgal/../../slice_mask.h:71,
                 from /home/vivar/tools/PyMesh/third_party/libigl/include/igl/copyleft/cgal/minkowski_sum.cpp:11,
                 from /home/vivar/tools/PyMesh/third_party/libigl/include/igl/copyleft/cgal/minkowski_sum.h:107,
                 from /home/vivar/tools/PyMesh/tools/IGL/MinkowskiSum.cpp:4:
/home/vivar/tools/PyMesh/third_party/libigl/include/igl/copyleft/cgal/../../find.h:11:0: warning: "EIGEN_YES_I_KNOW_SPARSE_MODULE_IS_NOT_STABLE_YET" redefined
 #define EIGEN_YES_I_KNOW_SPARSE_MODULE_IS_NOT_STABLE_YET
 ^
<command-line>:0:0: note: this is the location of the previous definition
In file included from /usr/include/eigen3/Eigen/Core:366:0,
                 from /home/vivar/tools/PyMesh/src/Core/EigenTypedef.h:4,
                 from /home/vivar/tools/PyMesh/tools/IGL/MinkowskiSum.h:5,
                 from /home/vivar/tools/PyMesh/tools/IGL/MinkowskiSum.cpp:2:
/home/vivar/tools/PyMesh/third_party/libigl/include/igl/copyleft/cgal/minkowski_sum.cpp: In instantiation of ‘void igl::copyleft::cgal::minkowski_sum(const Eigen::PlainObjectBase<Derived>&, const Eigen::PlainObjectBase<DerivedFA>&, const Eigen::Matrix<sType, 1, sCols, sOptions>&, const Eigen::Matrix<dType, 1, dCols, dOptions>&, bool, Eigen::PlainObjectBase<DerivedW>&, Eigen::PlainObjectBase<DerivedG>&, Eigen::PlainObjectBase<DerivedJ>&) [with DerivedVA = Eigen::Matrix<double, -1, -1, 1>; DerivedFA = Eigen::Matrix<int, -1, -1, 1>; sType = double; int sCols = 3; int sOptions = 1; dType = double; int dCols = 3; int dOptions = 1; DerivedW = Eigen::Matrix<double, -1, -1, 1>; DerivedG = Eigen::Matrix<int, -1, -1, 1>; DerivedJ = Eigen::Matrix<int, -1, 1>]’:
/home/vivar/tools/PyMesh/third_party/libigl/include/igl/copyleft/cgal/minkowski_sum.cpp:369:23:   required from ‘void igl::copyleft::cgal::minkowski_sum(const Eigen::PlainObjectBase<Derived>&, const Eigen::PlainObjectBase<DerivedFA>&, const Eigen::Matrix<sType, 1, sCols, sOptions>&, const Eigen::Matrix<dType, 1, dCols, dOptions>&, Eigen::PlainObjectBase<DerivedW>&, Eigen::PlainObjectBase<DerivedG>&, Eigen::PlainObjectBase<DerivedJ>&) [with DerivedVA = Eigen::Matrix<double, -1, -1, 1>; DerivedFA = Eigen::Matrix<int, -1, -1, 1>; sType = double; int sCols = 3; int sOptions = 1; dType = double; int dCols = 3; int dOptions = 1; DerivedW = Eigen::Matrix<double, -1, -1, 1>; DerivedG = Eigen::Matrix<int, -1, -1, 1>; DerivedJ = Eigen::Matrix<int, -1, 1>]’
/home/vivar/tools/PyMesh/tools/IGL/MinkowskiSum.cpp:45:30:   required from here
/usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:482:22: error: ‘Eigen::PlainObjectBase<Derived>& Eigen::PlainObjectBase<Derived>::operator=(Eigen::PlainObjectBase<Derived>&&) [with Derived = Eigen::Matrix<int, -1, 1>]’ is protected
     PlainObjectBase& operator=(PlainObjectBase&& other)
                      ^
In file included from /home/vivar/tools/PyMesh/third_party/libigl/include/igl/copyleft/cgal/minkowski_sum.h:107:0,
                 from /home/vivar/tools/PyMesh/tools/IGL/MinkowskiSum.cpp:4:
/home/vivar/tools/PyMesh/third_party/libigl/include/igl/copyleft/cgal/minkowski_sum.cpp:348:7: error: within this context
     J = slice(DerivedJ(J),SJ,1);
       ^
tools/IGL/CMakeFiles/lib_igl.dir/build.make:86: recipe for target 'tools/IGL/CMakeFiles/lib_igl.dir/MinkowskiSum.cpp.o' failed
make[3]: *** [tools/IGL/CMakeFiles/lib_igl.dir/MinkowskiSum.cpp.o] Error 1
CMakeFiles/Makefile2:3097: recipe for target 'tools/IGL/CMakeFiles/lib_igl.dir/all' failed
make[2]: *** [tools/IGL/CMakeFiles/lib_igl.dir/all] Error 2
CMakeFiles/Makefile2:263: recipe for target 'tools/CMakeFiles/tools.dir/rule' failed
make[1]: *** [tools/CMakeFiles/tools.dir/rule] Error 2
Makefile:144: recipe for target 'tools' failed
make: *** [tools] Error 2
```

**Comment by vpaeder** [comment]
I had the same problem. It seems to be a compatibility issue between IGL and the latest Eigen branch. This worked with Eigen v3.2.10.
